version: '3.8'

services:
  trading-analyzer:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped